apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-uploader-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-uploader-app
  template:
    metadata:
      labels:
        app: image-uploader-app
    spec:
      containers:
      - name: image-uploader
        image: <YOUR_CR_REGISTRY>/<YOUR_CR_REPO>/image-uploader:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: pg-conn
        - name: S3__BucketName
          valueFrom:
            configMapKeyRef:
              name: s3-config
              key: bucket
        - name: S3__Region
          valueFrom:
            configMapKeyRef:
              name: s3-config
              key: region
        - name: S3__ServiceUrl
          valueFrom:
            configMapKeyRef:
              name: s3-config
              key: serviceurl
        - name: S3__AccessKey
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: access
        - name: S3__SecretKey
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: secret
---
apiVersion: v1
kind: Service
metadata:
  name: image-uploader-app
spec:
  type: LoadBalancer
  selector:
    app: image-uploader-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-config

data:
  bucket: <S3_BUCKET_NAME>
  region: ru-central1
  serviceurl: https://storage.yandexcloud.net
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
stringData:
  access: <S3_ACCESS_KEY>
  secret: <S3_SECRET_KEY>
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
stringData:
  pg-conn: "Host=<PG_HOST>;Port=5432;Database=<PG_DB>;Username=<PG_USER>;Password=<PG_PASS>"
